import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { LocalStorageStatus } from "./LocalStorageStatus";
import { getLocalProofStorageUsage, subscribeToLocalProofChanges } from "../lib/local-proof-store";
vi.mock("../lib/local-proof-store", () => ({ getLocalProofStorageUsage: vi.fn(), subscribeToLocalProofChanges: vi.fn(() => () => {}) }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });
const limits = { savedBytes: 50331648, pendingBytes: 50331648, savedCount: 10000, pendingCount: 100 } as const;
it("shows aggregate media capacity and refreshes counts without loading evidence", async () => {
  vi.mocked(getLocalProofStorageUsage).mockResolvedValue({ savedBytes: 1048576, pendingBytes: 0, savedCount: 1, pendingCount: 0, limits, warnings: [] });
  const onBackup = vi.fn();
  const { rerender } = render(<LocalStorageStatus disabled={false} revision={0} onBackup={onBackup} />);
  fireEvent.click(screen.getByText("Stored in this browser. Keep a backup."));
  await screen.findByText("1.0 / 48.0 MiB · 1 / 10,000 items");
  vi.mocked(getLocalProofStorageUsage).mockResolvedValue({ savedBytes: 2097152, pendingBytes: 0, savedCount: 2, pendingCount: 0, limits, warnings: ["Synthetic capacity warning"] });
  act(() => vi.mocked(subscribeToLocalProofChanges).mock.calls[0][0]("automatic"));
  await screen.findByText("2.0 / 48.0 MiB · 2 / 10,000 items");
  expect(screen.getByRole("status")).toHaveTextContent("Synthetic capacity warning");
  fireEvent.click(screen.getByRole("button", { name: "Create an encrypted backup" }));
  expect(onBackup).toHaveBeenCalledOnce();
  vi.mocked(getLocalProofStorageUsage).mockResolvedValue({ savedBytes: 3145728, pendingBytes: 1048576, savedCount: 3, pendingCount: 1, limits, warnings: [] });
  rerender(<LocalStorageStatus disabled={false} revision={1} onBackup={onBackup} />);
  await screen.findByText("3.0 / 48.0 MiB · 3 / 10,000 items");
  await screen.findByText("1.0 / 48.0 MiB · 1 / 100 items");
});
it("reports an unavailable usage read rather than a misleading empty count", async () => {
  vi.mocked(getLocalProofStorageUsage).mockRejectedValue(new Error("synthetic failure"));
  render(<LocalStorageStatus disabled revision={0} onBackup={vi.fn()} />);
  fireEvent.click(screen.getByText("Stored in this browser. Keep a backup."));
  await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("does not mean your gallery is empty"));
  expect(screen.queryByLabelText("Local storage usage")).not.toBeInTheDocument();
  expect(screen.getByRole("button", { name: "Create an encrypted backup" })).toBeDisabled();
});
